// This file is auto-generated by @hey-api/openapi-ts

import { type as _type } from 'arktype';

export const Banner = _type({
    banner: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    bannerName: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    baseRate: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    constPrefix: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    constShorthand: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    guaranteed: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    maxConst: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    maxPity: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    minConst: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    pitySoftThreshold: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    rarity: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const BlogMeta = _type({
    createdAt: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    fileName: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    id: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    isPublish: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    title: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    updatedAt: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const BlogTag = _type({
    code: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    createdAt: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    id: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    label: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    updatedAt: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const BlogTagShape = _type({
    code: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    label: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const HealthResponse = _type({
    response: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const HelloReply = _type({
    message: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const HelloRequest = _type({
    name: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const Id = _type({
    id: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const ProbabilityRatePayload = _type({
    banner: Banner,
    current_eidolon: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    next_guaranteed: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    pity_current_count: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    pulls: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const ProtoPagination = _type({
    'all?': _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    'pageIndex?': _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    'pageSize?': _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    'search?': _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const BlogMetaList = _type({
    data: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    'pagination?': _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    total: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const BlogTagList = _type({
    data: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    'pagination?': _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    total: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const ReducedSim = _type({
    eidolon: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    rate: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});

export const ProbabilityRateResponse = _type({
    banner: Banner,
    data: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    }),
    roll_budget: _type({
        name: 'string',
        platform: '\'android\' | \'ios\'',
        'versions?': '(number | string)[]'
    })
});
