// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlogMeta } from "./BlogMeta";
import type { BlogTag } from "./BlogTag";

export type Blog = { meta?: BlogMeta, tags: Array<BlogTag>, content: string, };
