// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlogTag } from "./BlogTag";
import type { ProtoPagination } from "./ProtoPagination";

export type BlogTagList = { pagination?: ProtoPagination, total: number, data: Array<BlogTag>, };
