// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlogMeta } from "./BlogMeta";
import type { ProtoPagination } from "./ProtoPagination";

export type BlogMetaList = { 
/**
 * required
 */
pagination?: ProtoPagination, total: number, data: Array<BlogMeta>, };
