// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlogMeta = { 
/**
 * required
 */
id: string, title: string, fileName: string, isPublish: boolean, createdAt: bigint, updatedAt: bigint, };
