// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlogMetaShape } from "./BlogMetaShape";

export type BlogShape = { metaShape?: BlogMetaShape, tagIds: Array<string>, fileContent: string, };
