// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CargoBuildConfig } from "./CargoBuildConfig";
import type { DockerBuildConfig } from "./DockerBuildConfig";
import type { ScriptBuildConfig } from "./ScriptBuildConfig";

export type BuildConfig = { kind: number, scriptConfig?: ScriptBuildConfig, dockerConfig?: DockerBuildConfig, cargoConfig?: CargoBuildConfig, };
