// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProtoPagination = { pageIndex?: number, pageSize?: number, search?: string, all?: boolean, };
