// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Service } from "./Service";

export type RepoListResponse = { repos: Array<Service>, };
