// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTagData, CreateTagResponses, DeleteTagData, DeleteTagResponses, GetTagData, GetTagResponses, HealthApiData, HealthApiResponses, HealthCronData, HealthCronResponses, HealthRpcData, HealthRpcResponses, ListBlogMetaData, ListBlogMetaResponses, ListTagData, ListTagResponses, PullSimulationData, PullSimulationResponses, RpcgreetData, RpcgreetResponses, UpdateTagData, UpdateTagResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const listBlogMeta = <ThrowOnError extends boolean = false>(options: Options<ListBlogMetaData, ThrowOnError>) => (options.client ?? client).get<ListBlogMetaResponses, unknown, ThrowOnError>({ url: '/api/blog/meta', ...options });

/**
 * Blog tags
 */
export const listTag = <ThrowOnError extends boolean = false>(options: Options<ListTagData, ThrowOnError>) => (options.client ?? client).get<ListTagResponses, unknown, ThrowOnError>({ url: '/api/blog/tag', ...options });

export const createTag = <ThrowOnError extends boolean = false>(options: Options<CreateTagData, ThrowOnError>) => (options.client ?? client).post<CreateTagResponses, unknown, ThrowOnError>({
    url: '/api/blog/tag/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => (options.client ?? client).delete<DeleteTagResponses, unknown, ThrowOnError>({ url: '/api/blog/tag/{id}', ...options });

export const getTag = <ThrowOnError extends boolean = false>(options: Options<GetTagData, ThrowOnError>) => (options.client ?? client).get<GetTagResponses, unknown, ThrowOnError>({ url: '/api/blog/tag/{id}', ...options });

export const updateTag = <ThrowOnError extends boolean = false>(options: Options<UpdateTagData, ThrowOnError>) => (options.client ?? client).patch<UpdateTagResponses, unknown, ThrowOnError>({
    url: '/api/blog/tag/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Estimate gacha pull
 */
export const pullSimulation = <ThrowOnError extends boolean = false>(options: Options<PullSimulationData, ThrowOnError>) => (options.client ?? client).post<PullSimulationResponses, unknown, ThrowOnError>({
    url: '/api/gacha/pull_simulation',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get health of the API server.
 */
export const healthApi = <ThrowOnError extends boolean = false>(options?: Options<HealthApiData, ThrowOnError>) => (options?.client ?? client).get<HealthApiResponses, unknown, ThrowOnError>({ url: '/api/health/api', ...options });

/**
 * Get health of the cron worker.
 */
export const healthCron = <ThrowOnError extends boolean = false>(options?: Options<HealthCronData, ThrowOnError>) => (options?.client ?? client).get<HealthCronResponses, unknown, ThrowOnError>({ url: '/api/health/cron', ...options });

/**
 * Get health of the RPC server.
 */
export const healthRpc = <ThrowOnError extends boolean = false>(options?: Options<HealthRpcData, ThrowOnError>) => (options?.client ?? client).get<HealthRpcResponses, unknown, ThrowOnError>({ url: '/api/health/rpc', ...options });

/**
 * Simple greeter communication with the rpc client
 */
export const rpcgreet = <ThrowOnError extends boolean = false>(options: Options<RpcgreetData, ThrowOnError>) => (options.client ?? client).post<RpcgreetResponses, unknown, ThrowOnError>({
    url: '/api/rpcgreet',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
