// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildConfig } from "./BuildConfig";

export type Service = { serviceName: string, url: string, path?: string, deployment?: number, buildConfig?: BuildConfig, relativeRoot: string, };
