// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:5000' | (string & {});
};

export type Banner = {
    /**
     * base pity rate. hitting this rate ends the calc, failing this rate
     * resets the calc and enables `guaranteed_pity`
     * E.g:
     * 0.5 for hoyo char, 0.75 for hoyo weapons
     * 1.0 is a guaranteed, you get what you want
     */
    banner: number;
    bannerName: string;
    /**
     * base rate chance of the gacha
     */
    baseRate: number;
    constPrefix: string;
    constShorthand: string;
    /**
     * chance to get specifically the unit you want
     * E.g star rail banner with 3 SR means 0.33
     */
    guaranteed: number;
    maxConst: number;
    maxPity: number;
    minConst: number;
    /**
     * soft pity threshold of the banner
     */
    pitySoftThreshold: number;
    rarity: number;
};

export type BlogMeta = {
    createdAt: number;
    fileName: string;
    /**
     * required
     */
    id: string;
    isPublish: boolean;
    title: string;
    updatedAt: number;
};

export type BlogMetaList = {
    data: Array<BlogMeta>;
    pagination?: null | ProtoPagination;
    total: number;
};

export type BlogTag = {
    code: string;
    createdAt: number;
    id: string;
    label: string;
    updatedAt: number;
};

export type BlogTagList = {
    data: Array<BlogTag>;
    pagination?: null | ProtoPagination;
    total: number;
};

export type BlogTagShape = {
    code: string;
    label: string;
};

export type HelloReply = {
    message: string;
};

export type HelloRequest = {
    name: string;
};

export type Id = {
    id: string;
};

export type ProbabilityRatePayload = {
    /**
     * the banner rules
     */
    banner: Banner;
    /**
     * current dupe count
     */
    current_eidolon: number;
    /**
     * if your next targeted pull is really the correct target (you already
     * failed pity)
     */
    next_guaranteed: boolean;
    /**
     * current pity count, hitting the targeted pull sets this back to 00
     */
    pity_current_count: number;
    /**
     * total amount of pulls in possession
     */
    pulls: number;
};

export type ProbabilityRateResponse = {
    banner: Banner;
    data: Array<Array<ReducedSim>>;
    roll_budget: number;
};

export type ProtoPagination = {
    all?: boolean | null;
    pageIndex?: number | null;
    pageSize?: number | null;
    search?: string | null;
};

export type ReducedSim = {
    eidolon: number;
    rate: number;
};

export type ListBlogMetaData = {
    body?: never;
    path: {
        pageIndex: number | null;
        pageSize: number | null;
        search: string | null;
        all: boolean | null;
    };
    query?: never;
    url: '/api/blog/meta';
};

export type ListBlogMetaResponses = {
    /**
     * Success
     */
    200: BlogMetaList;
};

export type ListBlogMetaResponse = ListBlogMetaResponses[keyof ListBlogMetaResponses];

export type ListTagData = {
    body?: never;
    path: {
        pageIndex: number | null;
        pageSize: number | null;
        search: string | null;
        all: boolean | null;
    };
    query?: never;
    url: '/api/blog/tag';
};

export type ListTagResponses = {
    /**
     * Success
     */
    200: BlogTagList;
};

export type ListTagResponse = ListTagResponses[keyof ListTagResponses];

export type CreateTagData = {
    body: BlogTagShape;
    path?: never;
    query?: never;
    url: '/api/blog/tag/create';
};

export type CreateTagResponses = {
    /**
     * Success
     */
    200: BlogTag;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        /**
         * Tag id
         */
        id: string;
    };
    query?: never;
    url: '/api/blog/tag/{id}';
};

export type DeleteTagResponses = {
    /**
     * Success
     */
    200: Id;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type GetTagData = {
    body?: never;
    path: {
        /**
         * Tag id
         */
        id: string;
    };
    query?: never;
    url: '/api/blog/tag/{id}';
};

export type GetTagResponses = {
    /**
     * Success
     */
    200: BlogTag;
};

export type GetTagResponse = GetTagResponses[keyof GetTagResponses];

export type UpdateTagData = {
    body: BlogTag;
    path?: never;
    query?: never;
    url: '/api/blog/tag/{id}';
};

export type UpdateTagResponses = {
    /**
     * Success
     */
    200: BlogTag;
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];

export type PullSimulationData = {
    body: ProbabilityRatePayload;
    path?: never;
    query?: never;
    url: '/api/gacha/pull_simulation';
};

export type PullSimulationResponses = {
    /**
     * Success
     */
    200: ProbabilityRateResponse;
};

export type PullSimulationResponse = PullSimulationResponses[keyof PullSimulationResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Success
     */
    200: string;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type RpcgreetData = {
    body: HelloRequest;
    path?: never;
    query?: never;
    url: '/api/rpcgreet';
};

export type RpcgreetResponses = {
    /**
     * Success
     */
    200: HelloReply;
};

export type RpcgreetResponse = RpcgreetResponses[keyof RpcgreetResponses];
