// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBanner = z.object({
    banner: z.number(),
    bannerName: z.string(),
    baseRate: z.number(),
    constPrefix: z.string(),
    constShorthand: z.string(),
    guaranteed: z.number(),
    maxConst: z.int(),
    maxPity: z.int(),
    minConst: z.int(),
    pitySoftThreshold: z.int(),
    rarity: z.int().gte(0)
});

export const zBlogMeta = z.object({
    createdAt: z.coerce.bigint(),
    fileName: z.string(),
    id: z.string(),
    isPublish: z.boolean(),
    title: z.string(),
    updatedAt: z.coerce.bigint()
});

export const zBlogTag = z.object({
    code: z.string(),
    createdAt: z.coerce.bigint(),
    id: z.string(),
    label: z.string(),
    updatedAt: z.coerce.bigint()
});

export const zBlogTagShape = z.object({
    code: z.string(),
    label: z.string()
});

export const zHealthResponse = z.object({
    response: z.string()
});

export const zHelloReply = z.object({
    message: z.string()
});

export const zHelloRequest = z.object({
    name: z.string()
});

export const zId = z.object({
    id: z.string()
});

export const zProbabilityRatePayload = z.object({
    banner: zBanner,
    current_eidolon: z.int(),
    next_guaranteed: z.boolean(),
    pity_current_count: z.int(),
    pulls: z.int()
});

export const zProtoPagination = z.object({
    all: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    pageIndex: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    pageSize: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    search: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zBlogMetaList = z.object({
    data: z.array(zBlogMeta),
    pagination: z.optional(z.union([
        z.null(),
        zProtoPagination
    ])),
    total: z.int()
});

export const zBlogTagList = z.object({
    data: z.array(zBlogTag),
    pagination: z.optional(z.union([
        z.null(),
        zProtoPagination
    ])),
    total: z.int()
});

export const zReducedSim = z.object({
    eidolon: z.int(),
    rate: z.number()
});

export const zProbabilityRateResponse = z.object({
    banner: zBanner,
    data: z.array(z.array(zReducedSim)),
    roll_budget: z.int()
});

export const zListBlogMetaData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        pageIndex: z.union([
            z.int(),
            z.null()
        ]),
        pageSize: z.union([
            z.int(),
            z.null()
        ]),
        search: z.union([
            z.string(),
            z.null()
        ]),
        all: z.union([
            z.boolean(),
            z.null()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListBlogMetaResponse = zBlogMetaList;

export const zListTagData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        pageIndex: z.union([
            z.int(),
            z.null()
        ]),
        pageSize: z.union([
            z.int(),
            z.null()
        ]),
        search: z.union([
            z.string(),
            z.null()
        ]),
        all: z.union([
            z.boolean(),
            z.null()
        ])
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zListTagResponse = zBlogTagList;

export const zCreateTagData = z.object({
    body: zBlogTagShape,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zCreateTagResponse = zBlogTag;

export const zDeleteTagData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zDeleteTagResponse = zId;

export const zGetTagData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zGetTagResponse = zBlogTag;

export const zUpdateTagData = z.object({
    body: zBlogTag,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zUpdateTagResponse = zBlogTag;

export const zPullSimulationData = z.object({
    body: zProbabilityRatePayload,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zPullSimulationResponse = zProbabilityRateResponse;

export const zHealthApiData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zHealthApiResponse = zHealthResponse;

export const zHealthCronData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zHealthCronResponse = zHealthResponse;

export const zHealthRpcData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zHealthRpcResponse = zHealthResponse;

export const zRpcgreetData = z.object({
    body: zHelloRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Success
 */
export const zRpcgreetResponse = zHelloReply;
