// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTag, deleteTag, getTag, healthApi, healthCron, healthRpc, listBlogMeta, listTag, type Options, pullSimulation, rpcgreet, updateTag } from '../sdk.gen';
import type { CreateTagData, CreateTagResponse, DeleteTagData, DeleteTagResponse, GetTagData, GetTagResponse, HealthApiData, HealthApiResponse, HealthCronData, HealthCronResponse, HealthRpcData, HealthRpcResponse, ListBlogMetaData, ListBlogMetaResponse, ListTagData, ListTagResponse, PullSimulationData, PullSimulationResponse, RpcgreetData, RpcgreetResponse, UpdateTagData, UpdateTagResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listBlogMetaQueryKey = (options: Options<ListBlogMetaData>) => createQueryKey('listBlogMeta', options);

export const listBlogMetaOptions = (options: Options<ListBlogMetaData>) => queryOptions<ListBlogMetaResponse, DefaultError, ListBlogMetaResponse, ReturnType<typeof listBlogMetaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBlogMeta({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBlogMetaQueryKey(options)
});

export const listTagQueryKey = (options: Options<ListTagData>) => createQueryKey('listTag', options);

/**
 * Blog tags
 */
export const listTagOptions = (options: Options<ListTagData>) => queryOptions<ListTagResponse, DefaultError, ListTagResponse, ReturnType<typeof listTagQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTag({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTagQueryKey(options)
});

export const createTagMutation = (options?: Partial<Options<CreateTagData>>): UseMutationOptions<CreateTagResponse, DefaultError, Options<CreateTagData>> => {
    const mutationOptions: UseMutationOptions<CreateTagResponse, DefaultError, Options<CreateTagData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTag({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteTagMutation = (options?: Partial<Options<DeleteTagData>>): UseMutationOptions<DeleteTagResponse, DefaultError, Options<DeleteTagData>> => {
    const mutationOptions: UseMutationOptions<DeleteTagResponse, DefaultError, Options<DeleteTagData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTag({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTagQueryKey = (options: Options<GetTagData>) => createQueryKey('getTag', options);

export const getTagOptions = (options: Options<GetTagData>) => queryOptions<GetTagResponse, DefaultError, GetTagResponse, ReturnType<typeof getTagQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTag({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTagQueryKey(options)
});

export const updateTagMutation = (options?: Partial<Options<UpdateTagData>>): UseMutationOptions<UpdateTagResponse, DefaultError, Options<UpdateTagData>> => {
    const mutationOptions: UseMutationOptions<UpdateTagResponse, DefaultError, Options<UpdateTagData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTag({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Estimate gacha pull
 */
export const pullSimulationMutation = (options?: Partial<Options<PullSimulationData>>): UseMutationOptions<PullSimulationResponse, DefaultError, Options<PullSimulationData>> => {
    const mutationOptions: UseMutationOptions<PullSimulationResponse, DefaultError, Options<PullSimulationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await pullSimulation({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthApiQueryKey = (options?: Options<HealthApiData>) => createQueryKey('healthApi', options);

/**
 * Get health of the API server.
 */
export const healthApiOptions = (options?: Options<HealthApiData>) => queryOptions<HealthApiResponse, DefaultError, HealthApiResponse, ReturnType<typeof healthApiQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthApi({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthApiQueryKey(options)
});

export const healthCronQueryKey = (options?: Options<HealthCronData>) => createQueryKey('healthCron', options);

/**
 * Get health of the cron worker.
 */
export const healthCronOptions = (options?: Options<HealthCronData>) => queryOptions<HealthCronResponse, DefaultError, HealthCronResponse, ReturnType<typeof healthCronQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCron({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCronQueryKey(options)
});

export const healthRpcQueryKey = (options?: Options<HealthRpcData>) => createQueryKey('healthRpc', options);

/**
 * Get health of the RPC server.
 */
export const healthRpcOptions = (options?: Options<HealthRpcData>) => queryOptions<HealthRpcResponse, DefaultError, HealthRpcResponse, ReturnType<typeof healthRpcQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthRpc({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthRpcQueryKey(options)
});

/**
 * Simple greeter communication with the rpc client
 */
export const rpcgreetMutation = (options?: Partial<Options<RpcgreetData>>): UseMutationOptions<RpcgreetResponse, DefaultError, Options<RpcgreetData>> => {
    const mutationOptions: UseMutationOptions<RpcgreetResponse, DefaultError, Options<RpcgreetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await rpcgreet({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
